"""add_company_code

Revision ID: 20b0fa130fe2
Revises: 293c5c0a563c
Create Date: 2025-12-02 19:30:25.714007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b0fa130fe2'
down_revision: Union[str, None] = '293c5c0a563c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    import random
    
    # SQLite ne supporte pas ALTER COLUMN pour modifier nullability
    # On doit créer une nouvelle table avec la colonne code
    connection = op.get_bind()
    
    # 1. Créer une table temporaire avec la colonne code
    op.create_table(
        'companies_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('sector', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 2. Récupérer les entreprises existantes
    result = connection.execute(sa.text("SELECT id, name, sector, is_active, created_at FROM companies"))
    companies = result.fetchall()
    
    # 3. Générer des codes uniques et insérer dans la nouvelle table
    used_codes = set()
    for company in companies:
        company_id, name, sector, is_active, created_at = company
        # Générer un code unique à 6 chiffres
        while True:
            code = f"{random.randint(100000, 999999)}"
            if code not in used_codes:
                used_codes.add(code)
                connection.execute(
                    sa.text("""
                        INSERT INTO companies_new (id, code, name, sector, is_active, created_at)
                        VALUES (:id, :code, :name, :sector, :is_active, :created_at)
                    """),
                    {
                        "id": company_id,
                        "code": code,
                        "name": name,
                        "sector": sector,
                        "is_active": is_active,
                        "created_at": created_at
                    }
                )
                break
    
    # 4. Supprimer l'ancienne table et renommer la nouvelle
    op.drop_table('companies')
    op.rename_table('companies_new', 'companies')
    
    # 5. Créer les index
    op.create_index(op.f('ix_companies_code'), 'companies', ['code'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_code'), table_name='companies')
    op.drop_column('companies', 'code')
    # ### end Alembic commands ###
