"""add_password_reset_fields

Revision ID: 9bae5f6e0708
Revises: fe0f2d5eb7e1
Create Date: 2025-12-02 22:18:23.592536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bae5f6e0708'
down_revision: Union[str, None] = 'fe0f2d5eb7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Vérifier si les colonnes existent déjà
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'users' in existing_tables:
        existing_columns = [col['name'] for col in inspector.get_columns('users')]
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('users')]
    else:
        existing_columns = []
        existing_indexes = []
    
    # Ajouter les colonnes si elles n'existent pas
    if 'password_reset_token' not in existing_columns:
        op.add_column('users', sa.Column('password_reset_token', sa.String(), nullable=True))
    if 'password_reset_token_expires_at' not in existing_columns:
        op.add_column('users', sa.Column('password_reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    
    # Créer l'index si il n'existe pas
    if 'ix_users_password_reset_token' not in existing_indexes:
        try:
            op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=True)
        except Exception:
            pass  # L'index existe peut-être déjà


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.drop_column('users', 'password_reset_token_expires_at')
    op.drop_column('users', 'password_reset_token')
    # ### end Alembic commands ###
