"""add_email_verification

Revision ID: d0980f4b5082
Revises: 20b0fa130fe2
Create Date: 2025-12-02 20:44:41.775967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0980f4b5082'
down_revision: Union[str, None] = '20b0fa130fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    connection = op.get_bind()
    
    # Vérifier quelles colonnes existent déjà
    result = connection.execute(sa.text("PRAGMA table_info(users)"))
    existing_columns = [row[1] for row in result]
    
    # SQLite ne supporte pas ALTER COLUMN pour changer nullable
    # Si les colonnes n'existent pas, on crée une nouvelle table
    if 'email_verified' not in existing_columns:
        # Créer une nouvelle table avec le schéma complet
        op.create_table(
            'users_new',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('email', sa.String(), nullable=False),
            sa.Column('hashed_password', sa.String(), nullable=False),
            sa.Column('full_name', sa.String(), nullable=True),
            sa.Column('role', sa.String(), nullable=False),
            sa.Column('company_id', sa.Integer(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
            sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='1'),
            sa.Column('email_verification_token', sa.String(), nullable=True),
            sa.Column('email_verification_token_expires_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        
        # Copier les données (email_verified = True pour les utilisateurs existants)
        connection.execute(sa.text("""
            INSERT INTO users_new 
            (id, email, hashed_password, full_name, role, company_id, is_active, 
             email_verified, email_verification_token, email_verification_token_expires_at, created_at)
            SELECT 
                id, email, hashed_password, full_name, role, company_id, is_active,
                1 as email_verified,
                NULL as email_verification_token,
                NULL as email_verification_token_expires_at,
                created_at
            FROM users
        """))
        
        # Supprimer l'ancienne table et renommer la nouvelle
        op.drop_table('users')
        op.rename_table('users_new', 'users')
        
        # Créer les index
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=True)
    else:
        # Les colonnes existent déjà, juste créer l'index si nécessaire
        try:
            op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=True)
        except:
            # L'index existe peut-être déjà
            pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.drop_column('users', 'email_verification_token_expires_at')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
