"""add_type_and_tags_to_clients

Revision ID: fe0f2d5eb7e1
Revises: d0980f4b5082
Create Date: 2025-12-02 22:01:28.873125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0f2d5eb7e1'
down_revision: Union[str, None] = 'd0980f4b5082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Vérifier si les colonnes existent déjà
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_columns = [col['name'] for col in inspector.get_columns('clients')] if 'clients' in inspector.get_table_names() else []
    
    # Ajouter les colonnes si elles n'existent pas
    if 'type' not in existing_columns:
        op.add_column('clients', sa.Column('type', sa.String(), nullable=True))
    if 'tags' not in existing_columns:
        op.add_column('clients', sa.Column('tags', sa.JSON(), nullable=True))
    # Note: email_verified a déjà été géré dans une migration précédente, on ne le modifie pas ici


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'tags')
    op.drop_column('clients', 'type')
    # ### end Alembic commands ###
